export const units = [
  { value: 'ceo', label: "CEO" },
  { value: 'complianceManager', label: "Compliance Manager" },
  { value: 'trainingManager', label: "Training Manager" },
  { value: 'adminManager', label: "Admin Manager" },
  { value: 'whsManager', label: "WHS Manager" },
  { value: 'adminOfficer', label: "Admin Officer" },
  { value: 'itManager', label: "IT Manager" },
  { value: 'leadTrainer', label: "Lead Trainer/Assesor" },
  { value: 'trainerAssesor', label: "Trainer/Assesor" },
  { value: 'thirdParty', label: "Third Party" },
  { value: 'HRT', label: "High Risk Trainer" },
  { value: 'documentController', label: "Document Control" },
  { value: 'public', label: "Public" },
  { value: 'student', label: "Student" },
]
